POST http://localhost:4002/products
Content-Type: application/json

{
  "name": "Caderno Rosinha",
  "price": 25
}

###

GET http://localhost:4002/products 


###

GET http://localhost:4002/products/6dbc7c91-12c4-46d7-b815-fe53ff1a0cf3

###

PUT http://localhost:4002/products/95f08fc2-84c9-4a1a-ba92-a0adcf818462
Content-Type: application/json

{
  "name": "Caderno Rosa",
  "price": 35
}

###

DELETE http://localhost:4002/products/95f08fc2-84c9-4a1a-ba92-a0adcf818462